package daemon

import (
	"encoding/json"
	"fmt"
	"net/http"
	"testing"
	"time"

	"github.com/chronick/skiff/internal/config"
	"github.com/chronick/skiff/internal/runtime"
	"github.com/chronick/skiff/internal/status"
)

// --- POST /v1/containers/run ---

func TestHandleContainerRun_Basic(t *testing.T) {
	d, mockRT := newTestDaemon(nil)
	mux := d.setupRoutes()

	rr := doRequest(mux, "POST", "/v1/containers/run", map[string]interface{}{
		"image": "ghcr.io/chronick/sandbox:latest",
	})

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d: %s", rr.Code, rr.Body.String())
	}

	var resp AdhocRunResponse
	json.NewDecoder(rr.Body).Decode(&resp)

	if resp.Status != "started" {
		t.Errorf("expected status 'started', got %q", resp.Status)
	}
	if resp.Name == "" {
		t.Error("expected non-empty name in response")
	}

	// Verify runtime.Run was called
	calls := mockRT.CallsFor("Run")
	if len(calls) != 1 {
		t.Fatalf("expected 1 Run call, got %d", len(calls))
	}

	// Verify state was updated
	rs, ok := d.state.GetResource(resp.Name)
	if !ok {
		t.Fatal("expected resource in state")
	}
	if rs.State != status.StateRunning {
		t.Errorf("expected running, got %s", rs.State)
	}
	if rs.Labels["skiff.adhoc"] != "true" {
		t.Errorf("expected skiff.adhoc=true label")
	}
}

func TestHandleContainerRun_CustomName(t *testing.T) {
	d, _ := newTestDaemon(nil)
	mux := d.setupRoutes()

	rr := doRequest(mux, "POST", "/v1/containers/run", map[string]interface{}{
		"image": "ubuntu:22.04",
		"name":  "my-sandbox",
	})

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d", rr.Code)
	}

	var resp AdhocRunResponse
	json.NewDecoder(rr.Body).Decode(&resp)
	if resp.Name != "my-sandbox" {
		t.Errorf("expected name 'my-sandbox', got %q", resp.Name)
	}

	// Verify in state
	_, ok := d.state.GetResource("my-sandbox")
	if !ok {
		t.Fatal("expected my-sandbox in state")
	}
}

func TestHandleContainerRun_WithAllOptions(t *testing.T) {
	d, mockRT := newTestDaemon(nil)
	mux := d.setupRoutes()

	rr := doRequest(mux, "POST", "/v1/containers/run", map[string]interface{}{
		"image":        "ghcr.io/chronick/sandbox:latest",
		"command":      []string{"sleep", "infinity"},
		"volumes":      []string{"/host:/container"},
		"env":          map[string]string{"KEY": "value"},
		"cpus":         2,
		"memory":       "2G",
		"labels":       map[string]string{"purpose": "sandbox"},
		"timeout_secs": 3600,
		"remove":       true,
		"name":         "test-sandbox",
	})

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d: %s", rr.Code, rr.Body.String())
	}

	// Verify runtime received the correct config
	calls := mockRT.CallsFor("Run")
	if len(calls) != 1 {
		t.Fatalf("expected 1 Run call, got %d", len(calls))
	}
	rtCfg := calls[0].Args.(runtime.ContainerConfig)
	if rtCfg.Image != "ghcr.io/chronick/sandbox:latest" {
		t.Errorf("expected image, got %q", rtCfg.Image)
	}
	if len(rtCfg.Volumes) != 1 || rtCfg.Volumes[0] != "/host:/container" {
		t.Errorf("expected volumes, got %v", rtCfg.Volumes)
	}
	if rtCfg.Env["KEY"] != "value" {
		t.Errorf("expected env KEY=value, got %v", rtCfg.Env)
	}
	if rtCfg.Labels["purpose"] != "sandbox" {
		t.Errorf("expected purpose label, got %v", rtCfg.Labels)
	}
	if rtCfg.Labels["skiff.adhoc"] != "true" {
		t.Errorf("expected skiff.adhoc label, got %v", rtCfg.Labels)
	}

	// Verify tracker knows about it
	if !d.adhoc.IsAdhoc("test-sandbox") {
		t.Error("expected test-sandbox to be tracked as ad-hoc")
	}
}

func TestHandleContainerRun_MissingImage(t *testing.T) {
	d, _ := newTestDaemon(nil)
	mux := d.setupRoutes()

	rr := doRequest(mux, "POST", "/v1/containers/run", map[string]interface{}{
		"name": "no-image",
	})

	if rr.Code != http.StatusBadRequest {
		t.Errorf("expected 400, got %d", rr.Code)
	}
}

func TestHandleContainerRun_InvalidBody(t *testing.T) {
	d, _ := newTestDaemon(nil)
	mux := d.setupRoutes()

	rr := doRequest(mux, "POST", "/v1/containers/run", "invalid json")

	if rr.Code != http.StatusBadRequest {
		t.Errorf("expected 400, got %d", rr.Code)
	}
}

func TestHandleContainerRun_NameConflict(t *testing.T) {
	d, _ := newTestDaemon(nil)
	d.state.SetResource(&status.ResourceStatus{
		Name:  "existing",
		Type:  status.TypeContainer,
		State: status.StateRunning,
	})

	mux := d.setupRoutes()
	rr := doRequest(mux, "POST", "/v1/containers/run", map[string]interface{}{
		"image": "ubuntu:22.04",
		"name":  "existing",
	})

	if rr.Code != http.StatusConflict {
		t.Errorf("expected 409, got %d", rr.Code)
	}
}

func TestHandleContainerRun_AutoGeneratedName(t *testing.T) {
	d, _ := newTestDaemon(nil)
	mux := d.setupRoutes()

	rr := doRequest(mux, "POST", "/v1/containers/run", map[string]interface{}{
		"image": "ubuntu:22.04",
	})

	var resp AdhocRunResponse
	json.NewDecoder(rr.Body).Decode(&resp)

	if len(resp.Name) < 6 {
		t.Errorf("expected auto-generated name starting with 'adhoc-', got %q", resp.Name)
	}
	if resp.Name[:6] != "adhoc-" {
		t.Errorf("expected name prefix 'adhoc-', got %q", resp.Name)
	}
}

func TestHandleContainerRun_WithParent(t *testing.T) {
	d, _ := newTestDaemon(nil)
	mux := d.setupRoutes()

	rr := doRequest(mux, "POST", "/v1/containers/run", map[string]interface{}{
		"image":  "ubuntu:22.04",
		"name":   "child-1",
		"labels": map[string]string{"skiff.parent": "parent-agent"},
	})

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d", rr.Code)
	}

	// Verify parent label in state
	rs, ok := d.state.GetResource("child-1")
	if !ok {
		t.Fatal("expected child-1 in state")
	}
	if rs.Labels["skiff.parent"] != "parent-agent" {
		t.Errorf("expected skiff.parent=parent-agent, got %v", rs.Labels)
	}
}

func TestHandleContainerRun_RuntimeError(t *testing.T) {
	d, mockRT := newTestDaemon(nil)
	mockRT.RunErr = fmt.Errorf("image not found")
	mux := d.setupRoutes()

	rr := doRequest(mux, "POST", "/v1/containers/run", map[string]interface{}{
		"image": "nonexistent:latest",
	})

	if rr.Code != http.StatusInternalServerError {
		t.Errorf("expected 500, got %d", rr.Code)
	}
}

// --- POST /v1/containers/{name}/stop ---

func TestHandleContainerStop_Basic(t *testing.T) {
	d, mockRT := newTestDaemon(nil)

	// Start an adhoc container
	d.state.SetResource(&status.ResourceStatus{
		Name:   "test-stop",
		Type:   status.TypeContainer,
		State:  status.StateRunning,
		Labels: map[string]string{"skiff.adhoc": "true"},
	})
	d.adhoc.Track("test-stop", "", false, 0)

	mux := d.setupRoutes()
	rr := doRequest(mux, "POST", "/v1/containers/test-stop/stop", nil)

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d", rr.Code)
	}

	stops := mockRT.CallsFor("Stop")
	if len(stops) != 1 {
		t.Errorf("expected 1 Stop call, got %d", len(stops))
	}
}

func TestHandleContainerStop_NotFound(t *testing.T) {
	d, _ := newTestDaemon(nil)
	mux := d.setupRoutes()
	rr := doRequest(mux, "POST", "/v1/containers/nonexistent/stop", nil)

	if rr.Code != http.StatusNotFound {
		t.Errorf("expected 404, got %d", rr.Code)
	}
}

func TestHandleContainerStop_StopsChildren(t *testing.T) {
	d, mockRT := newTestDaemon(nil)

	// Create parent
	d.state.SetResource(&status.ResourceStatus{
		Name:  "parent",
		Type:  status.TypeContainer,
		State: status.StateRunning,
	})

	// Create children
	d.state.SetResource(&status.ResourceStatus{
		Name:   "child-1",
		Type:   status.TypeContainer,
		State:  status.StateRunning,
		Labels: map[string]string{"skiff.adhoc": "true", "skiff.parent": "parent"},
	})
	d.adhoc.Track("child-1", "parent", true, 0)

	d.state.SetResource(&status.ResourceStatus{
		Name:   "child-2",
		Type:   status.TypeContainer,
		State:  status.StateRunning,
		Labels: map[string]string{"skiff.adhoc": "true", "skiff.parent": "parent"},
	})
	d.adhoc.Track("child-2", "parent", true, 0)

	mux := d.setupRoutes()
	rr := doRequest(mux, "POST", "/v1/containers/parent/stop", nil)

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d", rr.Code)
	}

	// 3 Stop calls: parent + 2 children
	stops := mockRT.CallsFor("Stop")
	if len(stops) != 3 {
		t.Errorf("expected 3 Stop calls (parent + 2 children), got %d", len(stops))
	}

	// Children should be removed from state (remove=true)
	if _, ok := d.state.GetResource("child-1"); ok {
		t.Error("expected child-1 to be removed from state")
	}
	if _, ok := d.state.GetResource("child-2"); ok {
		t.Error("expected child-2 to be removed from state")
	}
}

// --- GET /v1/containers?parent={name} ---

func TestHandleContainers_FilterByParent(t *testing.T) {
	d, _ := newTestDaemon(nil)

	// Add containers with different parents
	d.state.SetResource(&status.ResourceStatus{
		Name:   "child-a",
		Type:   status.TypeContainer,
		State:  status.StateRunning,
		Labels: map[string]string{"skiff.parent": "agent-1"},
	})
	d.state.SetResource(&status.ResourceStatus{
		Name:   "child-b",
		Type:   status.TypeContainer,
		State:  status.StateRunning,
		Labels: map[string]string{"skiff.parent": "agent-1"},
	})
	d.state.SetResource(&status.ResourceStatus{
		Name:   "child-c",
		Type:   status.TypeContainer,
		State:  status.StateRunning,
		Labels: map[string]string{"skiff.parent": "agent-2"},
	})
	d.state.SetResource(&status.ResourceStatus{
		Name:  "no-parent",
		Type:  status.TypeContainer,
		State: status.StateRunning,
	})

	mux := d.setupRoutes()
	rr := doRequest(mux, "GET", "/v1/containers?parent=agent-1", nil)

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d", rr.Code)
	}

	var containers []map[string]interface{}
	json.NewDecoder(rr.Body).Decode(&containers)
	if len(containers) != 2 {
		t.Errorf("expected 2 containers for agent-1, got %d", len(containers))
	}

	// Verify no parent filter returns all containers
	rr2 := doRequest(mux, "GET", "/v1/containers", nil)
	var allContainers []map[string]interface{}
	json.NewDecoder(rr2.Body).Decode(&allContainers)
	if len(allContainers) != 4 {
		t.Errorf("expected 4 total containers, got %d", len(allContainers))
	}
}

func TestHandleContainers_FilterByParent_Empty(t *testing.T) {
	d, _ := newTestDaemon(nil)
	d.state.SetResource(&status.ResourceStatus{
		Name:  "db",
		Type:  status.TypeContainer,
		State: status.StateRunning,
	})

	mux := d.setupRoutes()
	rr := doRequest(mux, "GET", "/v1/containers?parent=nonexistent", nil)

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d", rr.Code)
	}

	// Should return empty/null list, not an error
	body := rr.Body.String()
	if body != "null\n" {
		// nil slice encodes as null in JSON
		var containers []map[string]interface{}
		json.Unmarshal([]byte(body), &containers)
		if len(containers) != 0 {
			t.Errorf("expected 0 containers for nonexistent parent, got %d", len(containers))
		}
	}
}

// --- AdhocTracker unit tests ---

func TestAdhocTracker_Track_Untrack(t *testing.T) {
	d, _ := newTestDaemon(nil)

	d.adhoc.Track("test-1", "parent", true, 0)
	if !d.adhoc.IsAdhoc("test-1") {
		t.Error("expected test-1 to be tracked")
	}

	d.adhoc.Untrack("test-1")
	if d.adhoc.IsAdhoc("test-1") {
		t.Error("expected test-1 to be untracked")
	}
}

func TestAdhocTracker_Children(t *testing.T) {
	d, _ := newTestDaemon(nil)

	d.adhoc.Track("child-1", "parent-a", false, 0)
	d.adhoc.Track("child-2", "parent-a", false, 0)
	d.adhoc.Track("child-3", "parent-b", false, 0)

	children := d.adhoc.Children("parent-a")
	if len(children) != 2 {
		t.Errorf("expected 2 children for parent-a, got %d", len(children))
	}

	children = d.adhoc.Children("parent-b")
	if len(children) != 1 {
		t.Errorf("expected 1 child for parent-b, got %d", len(children))
	}

	children = d.adhoc.Children("nobody")
	if len(children) != 0 {
		t.Errorf("expected 0 children for nobody, got %d", len(children))
	}
}

func TestAdhocTracker_StopChildren(t *testing.T) {
	d, mockRT := newTestDaemon(nil)

	// Set up child containers in state
	d.state.SetResource(&status.ResourceStatus{
		Name:   "child-1",
		Type:   status.TypeContainer,
		State:  status.StateRunning,
		Labels: map[string]string{"skiff.adhoc": "true", "skiff.parent": "parent"},
	})
	d.state.SetResource(&status.ResourceStatus{
		Name:   "child-2",
		Type:   status.TypeContainer,
		State:  status.StateRunning,
		Labels: map[string]string{"skiff.adhoc": "true", "skiff.parent": "parent"},
	})

	d.adhoc.Track("child-1", "parent", true, 0)
	d.adhoc.Track("child-2", "parent", false, 0)

	d.adhoc.StopChildren("parent")

	// Both children should be stopped
	stops := mockRT.CallsFor("Stop")
	if len(stops) != 2 {
		t.Errorf("expected 2 Stop calls, got %d", len(stops))
	}

	// child-1 (remove=true) should be removed from state
	if _, ok := d.state.GetResource("child-1"); ok {
		t.Error("expected child-1 to be removed from state (remove=true)")
	}

	// child-2 (remove=false) should be stopped in state
	rs, ok := d.state.GetResource("child-2")
	if !ok {
		t.Fatal("expected child-2 to remain in state (remove=false)")
	}
	if rs.State != status.StateStopped {
		t.Errorf("expected child-2 state=stopped, got %s", rs.State)
	}
}

func TestAdhocTracker_Timeout(t *testing.T) {
	d, mockRT := newTestDaemon(nil)

	d.state.SetResource(&status.ResourceStatus{
		Name:  "timeout-test",
		Type:  status.TypeContainer,
		State: status.StateRunning,
	})

	// Track with 1-second timeout
	d.adhoc.Track("timeout-test", "", true, 1)

	// Wait for timeout to fire
	time.Sleep(2 * time.Second)

	// Container should have been stopped
	stops := mockRT.CallsFor("Stop")
	if len(stops) != 1 {
		t.Errorf("expected 1 Stop call after timeout, got %d", len(stops))
	}

	// Should be removed from tracking
	if d.adhoc.IsAdhoc("timeout-test") {
		t.Error("expected timeout-test to be untracked after timeout")
	}
}

func TestAdhocTracker_PollExited_RemovesExited(t *testing.T) {
	d, _ := newTestDaemon(nil)

	d.state.SetResource(&status.ResourceStatus{
		Name:  "exited-container",
		Type:  status.TypeContainer,
		State: status.StateStopped,
	})
	d.adhoc.Track("exited-container", "", true, 0)

	d.adhoc.PollExited()

	// Should be removed from state and tracking
	if _, ok := d.state.GetResource("exited-container"); ok {
		t.Error("expected exited container to be removed from state")
	}
	if d.adhoc.IsAdhoc("exited-container") {
		t.Error("expected exited container to be untracked")
	}
}

func TestAdhocTracker_PollExited_KeepsRunning(t *testing.T) {
	d, _ := newTestDaemon(nil)

	d.state.SetResource(&status.ResourceStatus{
		Name:  "running-container",
		Type:  status.TypeContainer,
		State: status.StateRunning,
	})
	d.adhoc.Track("running-container", "", true, 0)

	d.adhoc.PollExited()

	// Should still be in state and tracked
	rs, ok := d.state.GetResource("running-container")
	if !ok {
		t.Fatal("expected running container to remain in state")
	}
	if rs.State != status.StateRunning {
		t.Errorf("expected state running, got %s", rs.State)
	}
	if !d.adhoc.IsAdhoc("running-container") {
		t.Error("expected running container to remain tracked")
	}
}

func TestAdhocTracker_StopAll(t *testing.T) {
	d, mockRT := newTestDaemon(nil)

	d.state.SetResource(&status.ResourceStatus{
		Name:  "adhoc-1",
		Type:  status.TypeContainer,
		State: status.StateRunning,
	})
	d.state.SetResource(&status.ResourceStatus{
		Name:  "adhoc-2",
		Type:  status.TypeContainer,
		State: status.StateRunning,
	})
	d.adhoc.Track("adhoc-1", "", true, 0)
	d.adhoc.Track("adhoc-2", "", false, 0)

	d.adhoc.StopAll()

	stops := mockRT.CallsFor("Stop")
	if len(stops) != 2 {
		t.Errorf("expected 2 Stop calls, got %d", len(stops))
	}
}

// --- Integration: down stops ad-hoc children ---

func TestHandleDown_StopsAdhocChildren(t *testing.T) {
	cfg := &config.Config{
		Version: 1,
		Paths:   config.PathsConfig{Base: "/tmp/test", Logs: "/tmp/test"},
		Daemon:  config.DaemonConfig{LogBufferLines: 100, StatusPollIntervalSecs: 5, ShutdownTimeoutSecs: 5},
		Containers: map[string]config.ContainerConfig{
			"agent": {Image: "agent:latest"},
		},
	}
	d, mockRT := newTestDaemon(cfg)

	// Agent has an ad-hoc child
	d.state.SetResource(&status.ResourceStatus{
		Name:   "agent-sandbox",
		Type:   status.TypeContainer,
		State:  status.StateRunning,
		Labels: map[string]string{"skiff.adhoc": "true", "skiff.parent": "agent"},
	})
	d.adhoc.Track("agent-sandbox", "agent", true, 0)

	mux := d.setupRoutes()
	rr := doRequest(mux, "POST", "/v1/down", map[string]interface{}{
		"names": []string{"agent"},
	})

	if rr.Code != http.StatusOK {
		t.Errorf("expected 200, got %d", rr.Code)
	}

	// 2 Stop calls: agent + agent-sandbox
	stops := mockRT.CallsFor("Stop")
	if len(stops) != 2 {
		t.Errorf("expected 2 Stop calls, got %d", len(stops))
	}

	// Child should be removed (remove=true)
	if _, ok := d.state.GetResource("agent-sandbox"); ok {
		t.Error("expected agent-sandbox to be removed from state")
	}
}

// --- randomID ---

func TestRandomID_Unique(t *testing.T) {
	ids := make(map[string]bool)
	for i := 0; i < 100; i++ {
		id := randomID()
		if ids[id] {
			t.Errorf("duplicate random ID: %s", id)
		}
		ids[id] = true
		if len(id) != 8 { // 4 bytes = 8 hex chars
			t.Errorf("expected 8 char hex ID, got %d chars: %s", len(id), id)
		}
	}
}
